import { Injectable } from '@angular/core'

@Injectable()
export class ProjectsService {
  mainImages = [
    { f: 'tip', t: 'login', title: 'Tipresento', desc: 'Invite friends, win leads, translate them to Amazon coupons' },
    { f: 'swp', t: 'login', title: 'Swap', desc: 'Banking system for a client' },
    { f: 'agency', t: 'home', title: 'Numbers Agency', desc: 'Apply as an agency to become partner with us' },
  ]

  allProjects: any = {
    tip: {
      f: 'tip',
      t: 'login',
      title: 'Tipresento',
      desc: 'Tipresento-desc',
      imgs: [
        'tipresento-design-implementation-1',
        'tipresento-design-implementation-2',
        'tipresento-design-implementation-3',
        'tipresento-design-implementation-4',
        'tipresento-design-implementation-5',
        'tipresento-design-implementation-6',
        'tipresento-design-implementation-7',
        'tipresento-design-implementation-8',
        'tipresento-design-implementation-9',
      ],
      extra_1: [
        'agent-dashboard',
        'agent-invite-friend',
        'agent-leads',
        'agent-notifications',
        'agent-riscuoti',
        'agent-send-category',
        'agent-signup',
        'agent-single-lead',
        'agent-wallet',
      ],
      extra_2: [
        'login',
        'logout',
        'profile',
        'singupask',
        'supplier-billing',
        'supplier-change-profile-pic',
        'supplier-edit-profile',
        'supplier-lead',
        'supplier-notifications',
      ],
      extra_3: [
        'supplier-single-lead',
        'billing-supplier',
        'edit-profile',
        'home-supplier',
        'home',
        'invite',
        'lead-details-supplier',
        'lead-details',
        'leads',
      ],
      extra_4: [
        'logout-m',
        'new-cat-inv',
        'notifications',
        'profile-m',
        'responsive-table-3',
        'responsive-table-2',
        'responsive-table',
        'riscuoti',
        'sign-agent',
        'singup1',
        'supplier-profile',
        'table-filters',
        'wallet',
      ],
      techs: [
        'Angular',
        'RxJs',
        'Ngbootstrap',
        'Ngx-translate',
        'Stripe',
        'Chart',
        'Datatables',
        'Moment',
        'Typescript',
        'HTML',
        'SCSS',
        'Bootstrap',
      ],
    },
    swp: {
      f: 'swp',
      t: 'login',
      title: 'Swap',
      desc: 'Swap-desc',
      imgs: ['act_as', 'btc_dashboard', 'btc', 'clients', 'forgot', 'login', 'new_store', 'new_user', 'settings'],
      extra_1: [
        'single_client',
        'single_store',
        'single_transaction',
        'stores',
        'transactions',
        'update_user',
        'clients-m',
        'deposit-m',
        'edit-profile-m',
      ],
      extra_2: [
        'home-m',
        'login-m',
        'new-client-m',
        'new-store-m',
        'new-user-m',
        'responsive-table-m',
        'settings-m',
        'sidebar-m',
        'single-store-m',
        'transfer-menu-m',
      ],
      techs: [
        'Angular',
        'RxJs',
        'GraphQL',
        'Nebular',
        'Ngbootstrap',
        'Ngx-translate',
        'Chart',
        'Datatables',
        'Moment',
        'Typescript',
        'HTML',
        'SCSS',
        'Bootstrap',
      ],
    },
    agency: {
      f: 'agency',
      t: 'home',
      ext: 'png',
      title: 'Agency',
      desc: 'Agency-desc',
      imgs: ['home', 'errors'],
      techs: ['Angular', 'RxJs', 'Ngx-translate', 'Typescript', 'HTML', 'SCSS', 'Bootstrap'],
    },
  }

  projectsMainList = this.mainImages.map((img) => {
    return {
      path: `assets/media/${img.f}/${img.t}.png`,
      ...img,
    }
  })

  constructor() {}
}
